name: chefsmart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  youtube_player_iframe: ^5.2.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:           # Cambia flutter_icons por flutter_launcher_icons
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/images/icono_app.png"
  image_path: "assets/images/icono_app.png"