// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtXYLI1XFGWBcoO3K-BS4G5MInQQTwE8',
    appId: '1:507811465735:web:628284bb569d7c9216f8a2',
    messagingSenderId: '507811465735',
    projectId: 'chefsmart-c74ad',
    authDomain: 'chefsmart-c74ad.firebaseapp.com',
    storageBucket: 'chefsmart-c74ad.firebasestorage.app',
    measurementId: 'G-K9HGDLVV2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7sPGdAK1ptkvZfEQpq3o-SubqVwvvj4',
    appId: '1:507811465735:android:c4b3a08a2a9ddfef16f8a2',
    messagingSenderId: '507811465735',
    projectId: 'chefsmart-c74ad',
    storageBucket: 'chefsmart-c74ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYvYngsSDKANjLgpDLBevi4vwkuW_wb34',
    appId: '1:507811465735:ios:b0c6da393e22036016f8a2',
    messagingSenderId: '507811465735',
    projectId: 'chefsmart-c74ad',
    storageBucket: 'chefsmart-c74ad.firebasestorage.app',
    iosBundleId: 'com.example.chefsmart',
  );
}
